/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 1471a1c384bb523ac8bf0e2194958bd8)
interface __BaseEnv_Env {
	CLAPS_KV: KVNamespace;
	NOTES_DB: D1Database;
	ADMIN_TOKEN: string;
	RATE_LIMIT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_TOKEN" | "RATE_LIMIT_SECRET">> {}
}
